---
- name: create /opt/yml
  file:
    path: /opt/yml
    state: directory


- name: copy yml files
  copy:
    src: "{{ item }}"
    dest: /opt/yml
  with_fileglob:
    - ./*

- name: copy metall lb config
  template: 
         src: 9.metallb-config.yaml.j2 
         dest: /opt/yml/9.metallb-config.yaml

- name:  get metall load balace
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml

- name: apply metall load balace
  k8s:
    state: present
    src: /opt/yml/9.metallb-config.yaml




- name: Deploying the Dashboard to Kubernetes.
  become: yes
  shell: kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
  #kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')
  # kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o yaml | grep "password:" | awk '{print $2}' | base64 --decode


- name: dashboard vsc deploy
  k8s:
    state: present
    src: /opt/yml/dashbroad-vsc.yml

- name: apply dash adm user
  k8s:
    state: present
    src: /opt/yml/5.dashboard-adminuser.yaml

- name: apply dash adm user
  k8s:
    state: present
    src: /opt/yml/kbroles.yml
