---
# - hosts: all
#   user: root
#   become: yes
#   roles:
#    - before
#    - depences
# #   - glusterfs
# #   - gservice

# - hosts: master
#   user: root
#   become: yes
#   roles:
#   - master

# - hosts: workers
#   user: root
#   become: yes
#   roles:
#    - workers
    
- hosts: master
  user: root
  gather_facts: no
  become: yes
  roles:
    - kube-apply

#- hosts: all
#  user: root
#  become: yes
#  roles:
#    - glusterfs
#    - gservice
#    - template