apiVersion: v1
kind: Pod
metadata:
 name: web-cinder
spec:
 containers:
   - name: web
     image: nginx
     ports:
       - name: web
         containerPort: 80
         hostPort: 8081
         protocol: TCP
     volumeMounts:
       - name: html-volume
         mountPath: "/usr/share/nginx/html"
 volumes:
   - name: html-volume
     cinder:
       # Введите ID диска ниже в поле $ID
       volumeID: $ID
       fsType: ext4