
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-www-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.64.61
    path: "/nmt/nfs/www"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-www-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi