---
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /root/.kube
        dest: /root/.kube
        mode: pull
      delegate_to: kub2

    - name: install Pod network
      become: yes
      become_user: root
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt


    - name: allow pods on nodes
      shell: kubectl taint node kub1 node-role.kubernetes.io/master:NoSchedule-
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set war
      add_host:
        name:   "K8S_TOKEN_HOLDER"
        token:  "{{  join_command_raw.stdout_lines[0] }}"