---
  tasks:
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: disable SELinux on reboot
      selinux:
       state: disabled
       
    - name: ensure private key and public one are present
      copy: 
        src: ~/.ssh 
        dest: "/root/" 
        mode: 0600
      with_items:
        - id_dsa.pub
        - id_dsa
    - name: Add IP address of all hosts to all hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Set authorized key for user ubuntu copying it from current user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: Ensure hostname set
      hostname: name={{ inventory_hostname }}

    - name: be sure firewalld is disabled
      systemd: name=firewalld enabled=no
      tags:
      - install
      - atomic
      - firewalld

    - name: be sure firewalld is stopped
      systemd: name=firewalld state=stopped
      ignore_errors: yes
      tags:
      - install
      - atomic
      - firewalld
      - ntp

    - name: Install base
      yum: name=epel-release state=present

    - name: Install App
      yum:
        name:
          - git
          - wget
          - net-tools
          - ntp

    - name: create ntp cron
      cron:
        name: "check time"
        minute: "*/5"
        job: "/sbin/ntpdate ru.pool.ntp.org"


#    - name: Set authorized key taken from file
#      authorized_key:
##        user: root
#        state: present
#        key: "{{ lookup('file', './ssh/id_rsa.pub') }}"
